output:
  out_dir: output
  device: cuda:1 # cuda:0 | cuda:1 | cpu
  verbose: true

input:
  mode: fill_only      # full | seg_fill | fill_only
  # path: "../stream/cmu_selected"
  path: "{out_dir}/construction/construction.npz"  # image folder if full; construction.npz if seg_fill; unused if fill_only

construction:
  point_conf_threshold: 0.05

segmentation:
  text_prompt: "sports field"
  sam_threshold: 0.8

filling:
  enabled: true
  radius: 0.03
  color_thresh: 0.05
  max_iters: 4
  backend: cpp           
  downsample: false
