output:
  out_dir: output
  device: cuda:1 # cuda:0 | cuda:1 | cpu
  verbose: true

input:
  mode: load                                 # load | inference
  path: "{out_dir}/predictions/preds.npz"  # predictions.npz if load; image folder if inference
  # mode: inference
  # path: ../stream/cmu_selected
  point_conf_threshold: 0.05

segmentation:
  text_prompt: "sports field"
  sam_threshold: 0.7

filling:
  enabled: true 
  radius: 0.03
  color_thresh: 0.05
  max_iters: 4
  backend: cpp                       # cpp (fast, requires build_bfs.sh) or python

